version: "3.8"
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: inventory_db
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
